server:
  port: 7573
  servlet:
    context-path: /  # Optional: Root context path
  ssl:
    enabled: false   # Disable HTTPS
spring:
  application:
    name: gateway-service
  profiles:
    active: pro

  datasource:
    url: jdbc:mysql://localhost:3306/gateway
    username: root
    password: Jay40984692$
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
      allow-bean-definition-overriding: true
      web-application-type: REACTIVE


logging:
  level:
    org: WARN
    hibernate:
      SQL: DEBUG
      type:
        descriptor: TRACE
    blog: WARN
    springframework: 
      security: DEBUG
