server:
  port: 7573
  servlet:
    context-path: /  # Optional: Root context path
  ssl:
    enabled: false   # Disable HTTPS

spring:
  application:
    name: gateway-service
   
  config:
    import: optional:configure-service:http://localhost:9191/

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  main:
      allow-bean-definition-overriding: true
      web-application-type: REACTIVE