spring:
  application:
    name: uaa-service
  profiles:
      active: pro

  datasource:
    url: jdbc:mysql://localhost:3306/uaa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: Jay40984692$
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org: WARN
    hibernate:
      SQL: DEBUG
      type:
        descriptor: TRACE
    blog: WARN
    springframework: 
      security: DEBUG

jwt:
  secret: "tz6sAA3jZxcamyqGVwShXl7MqACyE26WYRwrHl8FO1A="
  expiration: 2592000000 # 30 days in milliseconds