spring:
  application:
    name: ldap-service
  profiles:
    active: pro

  datasource:
    url: jdbc:mysql://localhost:3306/ldap
    username: root
    password: Jay40984692$
    driver-class-name: com.mysql.jdbc.Driver

  ldap:
    urls: ldap://your-ldap-server:389
    base: dc=example,dc=com
    username: cn=admin,dc=example,dc=com
    password: admin-password
    baseEnvironment:
      javax.naming.security.principal: cn=admin,dc=example,dc=com
      javax.naming.security.credentials: admin-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
      allow-bean-definition-overriding: true


logging:
  level:
    org: WARN
    hibernate:
      SQL: DEBUG
      type:
        descriptor: TRACE
    blog: WARN
    springframework: 
      security: DEBUG
