spring:
  application:
    name: discovery-service
   
  config:
    import: optional:configure-service:http://localhost:9191/

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
