server:
  port: 8761

spring:
  application:
    name: discovery-service
  profiles:
    active: pro

  datasource:
    url: jdbc:mysql://localhost:3306/discovery
    username: root
    password: Jay40984692$
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
      allow-bean-definition-overriding: true
      
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org: WARN
    hibernate:
      SQL: DEBUG
      type:
        descriptor: TRACE
    blog: WARN
    springframework: 
      security: DEBUG
